;
; Favorites list for the Allstar nodes manged by this instance of
; Allmon3.
;

; Each managed node can have its own list of favorite nodes

; Create a section named after the node number and list each favorite
; in the section as "node number: text description". Note that any
; node number is valid including Echolink nodes.

; [1999]
; 27339: East Coast Reflector
; 27225: Philadelphia Hub
; 3002560: WINS System
