name: 'Make and Publish Pkgs'
run-name: Package ${{ github.event.repository.name }}(${{ github.ref_name }}) for ${{ inputs.os }}/${{ inputs.arch }}, Publish to ${{ inputs.deployment-environment }}
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Debian Release Version'
        type: choice
        options:
          - bookworm
          - bullseye
      gh-rel:
        description: 'GitHub Release Tag (for debs)'
        type: string
      aptly-repo:
        description: 'Aptly Repository Stream'
        type: choice
        options:
          - beta
          - devel
      arch:
        description: 'Platform Architecture (Do not change)'
        type: choice
        options:
          - amd64

env:
  APTLY_API_USER: ${{secrets.APTLY_API_USER}}
  APTLY_API_PASS: ${{secrets.APTLY_API_PASS}}
  APTLY_GPG_PASSPHRASE: ${{secrets.APTLY_GPG_PASSPHRASE}}

jobs:
  make-packages:
    uses: AllStarLink/asl3-workflows/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: ./builder/dockerbuild.sh -a ${{ inputs.arch	}} -o ${{ inputs.os }} --gh-rel ${{ inputs.gh-rel }} -r ${{ inputs.aptly-repo }} 
      arch: ${{ inputs.arch == 'armhf' && 'arm64' || inputs.arch == 'aarch64' && 'arm64' || inputs.arch == 'amd64' && 'x86_64' || inputs.arch == 'riscv64' && 'x86_64' || inputs.arch }}
      artifact-path: '/actions-runner/_work/asl3-update-nodelist/_debs/'
    secrets: inherit
